### ISSUE TITLE
Coturn doesn't free ipv6 udp sockets

### ISSUE THREAD

**Issue by vol4iniche** [coturn/coturn#217] opened 2018-02-21 12:46 UTC
Coturn doesn't free ipv6 udp6 sockets and they use file descriptors. And service can't get new connections because the process uses all FDs.
Sessions were expired but service still has udp6 sockets for them. 

Also, coturn sessions that use ipv6 doesn't have expiration timeout, they created with the expired state.

id=someId, user <someUser>:
      realm: example.net
      started 89160 secs ago
      expired
      client protocol UDP, relay protocol UDP
      client addr [ipv6addr]:47159, server addr [ipv6addr]:443
      relay addr [ipv6addr]:49302
      fingerprints enforced: OFF
      mobile: OFF
      usage: rp=5, rb=284, sp=4, sb=540
       rate: r=0, s=0, total=0 (bytes per sec)

**Comment by misi** [comment] 2018-04-06 05:32
I will check it. 
(It would be great if you could send PR if you have found the root of the issue already.)

**Comment by misi** [comment] 2018-04-10 14:43
@vol4iniche  @ggarber @eakraly Can you please help me?
1. turn server config file
I try to reproduce the issue, could you help me and add to this issue your configuration?
And any further detailed description about howto reproduce it.
2. Relay IP
I want to know at least if your relay IP addresses are autodiscovered, or "hard coded" in your config.
Thanks in advance!

**Comment by vol4iniche** [comment] 2018-04-11 10:06
@misi 

$ cat /etc/turnserver.conf
lt-cred-mech
use-auth-secret
static-auth-secret=somesecret
realm=example.net
listening-port=443
cert=/etc/ssl/example.net.crt
pkey=/etc/ssl/example.net.key

turn start command:
/usr/bin/turnserver --external-ip external-ip/local-ip -c /etc/turnserver.conf -o -v -l /var/log/coturn/turn.log --simple-log

ipv6 - autodiscovered, we use UDP and TCP

**Comment by vol4iniche** [comment] 2018-04-20 15:38
@misi 
Oh, we use autodiscovered relay IP addresses

**Comment by damencho** [comment] 2018-07-16 21:13
@misi I was trying to debug this issue the last few days and I think it is the same as https://github.com/coturn/coturn/issues/192
I was testing this fix and it seems to fix the problem for us:
https://github.com/coturn/coturn/compare/master...damencho:fix-leak-udp6?expand=1
WDYT?

**Comment by misi** [comment] 2018-07-17 07:32
I will check it! Thanks!

**Comment by damencho** [comment] 2018-07-19 17:54
@misi Is there any way I can help with that? Thanks.

**Comment by misi** [comment] 2018-07-20 06:40
I am sorry I was busy with my bread winner works...
In accordance with RFC 6156:
```
If the REQUESTED-ADDRESS-FAMILY attribute is absent, the server MUST
   allocate an IPv4-relayed transport address for the TURN client.  If
   allocation of IPv4 addresses is disabled by local policy, the server
   returns a 440 (Address Family not Supported) Allocate error response.
It happens when no REQUESTED-ADDRESS-FAMILY specified.
```
AFAIU if REQUESTED-ADDRESS-FAMILY is absent we get to the case where you made the fix.
Am I right?

**Comment by misi** [comment] 2018-07-20 06:51
I guess you are right and the issue is connected with this edge case, but AFAIU your proposed change will break the RFC 6156 rule.

coTURN try to allocates IPv4 family address if `STUN_ATTRIBUTE_REQUESTED_ADDRESS_FAMILY_VALUE_DEFAULT`
See:
https://github.com/coturn/coturn/blob/d9c73764de84f4b995ffe4852365539421278b57/src/apps/relay/ns_ioalib_engine_impl.c#L524-L536

**Comment by damencho** [comment] 2018-07-20 14:06
And personally I don't see the logic behind that statement in the RFC, if you have received a request on the ipv6 socket, it is normal to return ipv6 candidate not ipv4 by default if not stated by REQUESTED-ADDRESS-FAMILY. But yeah, it is RFC and this is what it is :)

**Comment by damencho** [comment] 2018-07-20 21:12
Well, keeping up with the RFC, I think, will mean no turn will be used with ipv6 when using webrtc and google chrome ... :( I don't see that family request attribute to be set by chrome. But this is what it is. 

Maybe adding a config and keeping it by default rfc compatible, but give the option to users to switch to be able to use it the other way around where it will work with current browsers and ipv6, will be nice. Just a proposal.

**Comment by misi** [comment] 2018-07-21 06:36
I am not tottally sure but AFAIU it is already there. 
It is not (well) documented and we could make it more obvious, but I think it is already done:
1. If you use autodetected relay IP-s then it should work the same way as you suggested. If it receive on IPv6 listener then it allocates an IPv6 address
2. But if you explicitly specify relay IP address then it works according with the RFC.

**Comment by misi** [comment] 2018-07-24 09:01
Yesterday I also started to investigate it. Sorry for the delay.

In this line the
https://github.com/coturn/coturn/blob/114881bc9a455b8694634dd4cc3c3acb22845826/src/server/ns_turn_server.c#L4298

The `get_family` input is the STUN_ATTRIBUTE_REQUESTED_ADDRESS_FAMILY_VALUE_DEFAULT but it gives back v4 family.

That seems to me strange because here it is not yet decided that it will allocate IPv4 or IPv6.

So the `newelem` points to ss->alloc->relay_sessions->0 that is the ipv4 allocation memory space. 
So it not use ss->alloc->relay_sessions->1 for ipv6 address family and that is what you fix with that you specify explicitly if client IP is IPv6 then use IPv6 allocation. 

I not fully understand yet it. I need more time.

AFAIU to hard wire client address family dependency cause an issue in case if Relay IP-s are explicitly specified (not autodiscovered). 
Your actual patch makes impossible to work according the RFC so allocate IPv4 even if it received on IPv6, when the family not explicitly specified in the request.

We need to work on it little bit more.
It could be a new option if you want to in general the client session address family 

What do you think?

**Comment by misi** [comment] 2018-07-24 13:51
Please test this: https://github.com/coturn/coturn/commit/ab07d244b4857271381d4208a6e3a27adf2bc4cf
(I am not sure if it is elegant enough yet. Seems to be working at least.) 

@damencho  Thank You for the patch and for pointing out the root of the issue!! 
Greatly appreciated your cooperation!!

According my few tests this commit also solves the issue like your patch (of course further testing still needed). The only difference that my version does not cause any change in existing coTURN behaviour. According my test your version enforce in both case the same behaviour and it is a change
I don't have strong opinion about which is the right behaviour.

I am still not sure if it is a bug or feature.
I think there is a reason why the writers of the RFC choose IPv4. Because still the internet still use IPv4 
https://www.google.com/intl/en/ipv6/statistics.html#tab=per-country-ipv6-adoption
However I also wrote the RFC author a letter to clarify it more.

I am not happy with actual behaviour, because for me it is confusing little bit, and it is one of the not yet documented feature of coTURN. I think we should discuss further if there is a need or not, to set from config the behaviour in case of absence of explicit IP address family representation in requests to work according RFC or according client connection.

**Comment by damencho** [comment] 2018-07-24 14:56
I tested your proposed change and it works for our case. Thanks.

**Comment by misi** [comment] 2018-09-12 12:39
I added an option to control family selection: https://github.com/coturn/coturn/commit/93c1103bb85e0df92bfea138a9caabd7b2f4c286

`keep-address-family ` 

Use this option if you want to use the same address family in allocation that you use during the server communication.

Could you please check the actual master branch?
If there is no other comment here then please close this issue..

**Comment by damencho** [comment] 2018-09-12 16:02
@misi I left a minor comment, other than that it looks ok to me.
One question, is there a public repo with Debian packages that will take that change so we can use that?

**Comment by misi** [comment] 2018-09-13 05:56
After releasing it I want to push ASAP to debian official repository and
create a backport package too.

If this plan fails I will create a private repository..

Дамян Минков <notifications@github.com> ezt írta (időpont: 2018. szept.
12., Sze 18:02):

**Comment by misi** [comment] 2018-09-14 09:27
It sees to be fixed. 
@damencho @vol4iniche  Many thanks for your help!

**Closed by misi** 2018-09-14 09:27 UTC
Labels: bug

**Comment by damencho** [comment] 2018-11-06 18:19
Hey @misi is there some known debian repo with packages for 4.5.0.8 or later for bionic? Thanks.

**Comment by misi** [comment] 2018-11-06 21:22
Unfortunately debian repo is not yet updated, but it is on my todo list..

I am so sorry..

2018. nov. 6., Ke 19:19 dátummal Дамян Минков <notifications@github.com>
ezt írta:

**Comment by damencho** [comment] 2018-11-06 21:59
No worries, thanks for the quick reply.

**Comment by muranava** [comment] 2021-04-02 19:18
anyone know if coturn for the ubuntu 18.04 package will be updated?
thz
