### ISSUE TITLE
Error while docker build coturn

### ISSUE THREAD

**Issue by thachnv92** [coturn/coturn#426] opened 2019-08-08 09:16 UTC
Hello,
I got error when build coturn in docker/coturn/
In Step 18/26:
```
Step 18/26 : RUN export DEBIAN_FRONTEND=noninteractive &&       apt-get update &&       apt-get install -y libc6>=2.15 libevent-core-2.0-5>=2.0.10-stable libevent-extra-2.0-5>=2.0.10-stable libevent-openssl-2.0-5>=2.0.10-stable libevent-pthreads-2.0-5>=2.0.10-stable libhiredis0.13>=0.13.1 libmariadbclient18>=5.5.36 libpq5>=8.4~ libsqlite3-0>=3.6.0 libssl1.1>=1.1.0 libmongoc-1.0 libbson-1.0
 ---> Running in de215bb3e855
Get:1 http://security-cdn.debian.org/debian-security stable/updates InRelease [39.1 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stable InRelease [118 kB]
Get:3 http://security-cdn.debian.org/debian-security stable/updates/main amd64 Packages [53.4 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stable-updates InRelease [46.8 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stable/main amd64 Packages [7897 kB]
Fetched 8154 kB in 2s (4773 kB/s)
Reading package lists...
E: Unable to locate package libevent-core-2.0-5
E: Couldn't find any package by glob 'libevent-core-2.0-5'
E: Couldn't find any package by regex 'libevent-core-2.0-5'
E: Unable to locate package libevent-extra-2.0-5
E: Couldn't find any package by glob 'libevent-extra-2.0-5'
E: Couldn't find any package by regex 'libevent-extra-2.0-5'
E: Unable to locate package libevent-openssl-2.0-5
E: Couldn't find any package by glob 'libevent-openssl-2.0-5'
E: Couldn't find any package by regex 'libevent-openssl-2.0-5'
E: Unable to locate package libevent-pthreads-2.0-5
E: Couldn't find any package by glob 'libevent-pthreads-2.0-5'
E: Couldn't find any package by regex 'libevent-pthreads-2.0-5'
E: Unable to locate package libhiredis0.13
E: Couldn't find any package by glob 'libhiredis0.13'
E: Couldn't find any package by regex 'libhiredis0.13'
E: Package 'libmariadbclient18' has no installation candidate
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&        apt-get update &&       apt-get install -y libc6>=2.15 libevent-core-2.0-5>=2.0.10-stable libevent-extra-2.0-5>=2.0.10-stable libevent-openssl-2.0-5>=2.0.10-stable libevent-pthreads-2.0-5>=2.0.10-stable libhiredis0.13>=0.13.1 libmariadbclient18>=5.5.36 libpq5>=8.4~ libsqlite3-0>=3.6.0 libssl1.1>=1.1.0 libmongoc-1.0 libbson-1.0' returned a non-zero code: 100
```

Please help me correct it.
Thanks.

**Comment by 4ydx** [comment] 2019-08-12 03:55
Are you using debian?  There is an error message: "Package 'libmariadbclient18' has no installation candidate".

**Comment by thachnv92** [comment] 2019-08-12 04:33
> Are you using debian? There is an error message: "Package 'libmariadbclient18' has no installation candidate".

Yes. I got code this here.

**Comment by 4ydx** [comment] 2019-08-12 12:09
Face palm.  Yeah of course.  I would try debian:latest to see if that fixes it.

**Comment by thachnv92** [comment] 2019-08-13 07:25
> Face palm. Yeah of course. I would try debian:latest to see if that fixes it.
> 
> ```
> FROM debian:latest AS coturn-build
> ```

I changed it but still error.
```
Step 1/26 : FROM debian:latest AS coturn-build
latest: Pulling from library/debian
5ae19949497e: Pull complete
Digest: sha256:903779f30a7ee46937bfb21406f125d5fdace4178074e1cc71c49039ebf7f48f
Status: Downloaded newer image for debian:latest
 ---> 00bf7fdd8baf
```
```
E: Unable to locate package libevent-core-2.0-5
E: Couldn't find any package by glob 'libevent-core-2.0-5'
E: Couldn't find any package by regex 'libevent-core-2.0-5'
E: Unable to locate package libevent-extra-2.0-5
E: Couldn't find any package by glob 'libevent-extra-2.0-5'
E: Couldn't find any package by regex 'libevent-extra-2.0-5'
E: Unable to locate package libevent-openssl-2.0-5
E: Couldn't find any package by glob 'libevent-openssl-2.0-5'
E: Couldn't find any package by regex 'libevent-openssl-2.0-5'
E: Unable to locate package libevent-pthreads-2.0-5
E: Couldn't find any package by glob 'libevent-pthreads-2.0-5'
E: Couldn't find any package by regex 'libevent-pthreads-2.0-5'
E: Unable to locate package libhiredis0.13
E: Couldn't find any package by glob 'libhiredis0.13'
E: Couldn't find any package by regex 'libhiredis0.13'
E: Package 'libmariadbclient18' has no installation candidate
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&        apt-get update &&       apt-get install -y libc6>=2.15 libevent-core-2.0-5>=2.0.10-stable libevent-extra-2.0-5>=2.0.10-stable libevent-openssl-2.0-5>=2.0.10-stable libevent-pthreads-2.0-5>=2.0.10-stable libhiredis0.13>=0.13.1 libmariadbclient18>=5.5.36 libpq5>=8.4~ libsqlite3-0>=3.6.0 libssl1.1>=1.1.0 libmongoc-1.0 libbson-1.0' returned a non-zero code: 100
```

**Comment by 4ydx** [comment] 2019-08-22 14:35
You might try debian:stretch.  buster recently became the stable version so that might be it.

**Comment by thachnv92** [comment] 2019-08-27 02:12
> You might try debian:stretch. buster recently became the stable version so that might be it.

No change :((

```
E: Unable to locate package libevent-core-2.0-5
E: Couldn't find any package by glob 'libevent-core-2.0-5'
E: Couldn't find any package by regex 'libevent-core-2.0-5'
E: Unable to locate package libevent-extra-2.0-5
E: Couldn't find any package by glob 'libevent-extra-2.0-5'
E: Couldn't find any package by regex 'libevent-extra-2.0-5'
E: Unable to locate package libevent-openssl-2.0-5
E: Couldn't find any package by glob 'libevent-openssl-2.0-5'
E: Couldn't find any package by regex 'libevent-openssl-2.0-5'
E: Unable to locate package libevent-pthreads-2.0-5
E: Couldn't find any package by glob 'libevent-pthreads-2.0-5'
E: Couldn't find any package by regex 'libevent-pthreads-2.0-5'
E: Unable to locate package libhiredis0.13
E: Couldn't find any package by glob 'libhiredis0.13'
E: Couldn't find any package by regex 'libhiredis0.13'
E: Package 'libmariadbclient18' has no installation candidate
```

**Comment by thachnv92** [comment] 2019-08-27 02:13
> You might try debian:stretch. buster recently became the stable version so that might be it.

I change this code as you said, But nothing to change.
Issue is still visible.

**Comment by 4ydx** [comment] 2019-08-28 15:56
You can try replacing the error messages with something like:

apt-get install -y libc6>=2.15 libevent-core-2.0-5>=2.0.10-stable ... (etc)

->

apt-get install -y libc6>=2.15 libevent-core-*  ... (etc)

This may or may not work.  I am not familiar with this projects dependencies.

**Comment by iiiyx** [comment] 2019-09-13 17:21
@4ydx, thank you! your solution workes! I had exactly the same problem.

**Comment by fatpandaria** [comment] 2019-10-16 07:46
Does this docker build support MacOs?I got the same error while using the docker-compose.

**Comment by misi** [comment] 2019-10-28 15:22
@fatpandaria can you please retry it with the latest master?
(Sorry for the late reply...)
I think this issue is fixed now..

**Comment by schildbach** [comment] 2020-03-29 16:16
I've got the exact same issue. I'm on the `4.5.1.1` tag. My host OS is Ubuntu 18.04.4 LTS, but that should not matter much.

**Comment by schildbach** [comment] 2020-03-29 16:20
I think the issue is that Debian stable has `libevent-core-2.1-6`, _not_ `libevent-core-2.0-5`. Similar with the other packages.

**Comment by eakraly** [comment] 2022-08-23 00:53
This issue has no activity for 2.5 years now
Moreover, docker images are built for every PR
Considering this issue as resolved
If there is still an issue please open a new one. TY!

**Closed by eakraly** 2022-08-23 00:53 UTC
