### ISSUE TITLE
Random sessions failure when more than 2 computers are involved

### ISSUE THREAD

**Issue by deajan** [coturn/coturn#274] opened 2018-09-11 20:46 UTC
Hello,

I'm trying to get my coturn / nextcloud setup working for some time now.

My coturn server has a public IP (no nat nor proxy), and has to deal with behind NAT clients.
I always get video to work with 2 attendants (from different public IPs and different firewalls).
When I try to have 3 attendants, it usually does not work (black screen, one attendant can see the two others, but another one only sees one, whatever, it's never the same issue...).

I've tried to figure out what happens, trying with various server settings (no-tcp, no-udp)...
My client computers are behind restrictive firewalls which allow output to 443/tcp and 443/udp only.

Here's one of my session logs I get with the cli interface of coturn when having 3 attendants:
XX.XX.XX.XX = server IP
AA.AA.AA.AA = client A, BB.BB.BB.BB = client B and so on

Some of the sessions are `rate: r=0, s=0, total=0 (bytes per sec)` and don't seem to work.

```
> ps

    1) id=000000000000000023, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 594 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30761, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:62509
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=3, rb=152, sp=2, sb=164
       rate: r=0, s=0, total=0 (bytes per sec)

    2) id=000000000000000026, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 0 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30898, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:52587
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=4, rb=256, sp=3, sb=264
       rate: r=0, s=0, total=0 (bytes per sec)

    3) id=000000000000000004, user <1536783364>:
      realm: ebox.fmi.fr
      started 552 secs ago
      expiring in 588 secs
      client protocol TCP, relay protocol UDP
      client addr BB.BB.BB.BB:51658, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:57009
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=92165, rb=54074272, sp=155643, sb=122509328
       rate: r=98856, s=223965, total=322821 (bytes per sec)
      peers:
          10.69.1.82
          XX.XX.XX.XX
          XX.XX.XX.XX:50674

    4) id=000000000000000025, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 0 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30967, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:55686
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=4, rb=256, sp=3, sb=264
       rate: r=0, s=0, total=0 (bytes per sec)

    5) id=000000000000000024, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 594 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30863, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:64504
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=4, rb=260, sp=3, sb=264
       rate: r=0, s=0, total=0 (bytes per sec)
      peers:
          192.168.5.52

    6) id=000000000000000001, user <1536783317>:
      realm: ebox.fmi.fr
      started 554 secs ago
      expiring in 586 secs
      client protocol TCP, relay protocol UDP
      client addr CC.CC.CC.CC:43643, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:50674
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=155664, rb=122260405, sp=92144, sb=54260512
       rate: r=222696, s=98835, total=321531 (bytes per sec)
      peers:
          192.168.5.52
          XX.XX.XX.XX
          XX.XX.XX.XX:57009

    7) id=000000000000000021, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 594 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30809, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:50512
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=3, rb=152, sp=2, sb=164
       rate: r=0, s=0, total=0 (bytes per sec)

    8) id=000000000000000022, user <1536784176>:
      realm: ebox.fmi.fr
      started 6 secs ago
      expiring in 594 secs
      client protocol UDP, relay protocol UDP
      client addr AA.AA.AA.AA:30773, server addr XX.XX.XX.XX:443
      relay addr XX.XX.XX.XX:51029
      fingerprints enforced: OFF
      mobile: OFF
      Max throughput: 1024000 bytes per second
      usage: rp=3, rb=152, sp=2, sb=164
       rate: r=0, s=0, total=0 (bytes per sec)
	 
  Total sessions: 8
```

My Coturn conf file

```
tls-listening-port=443
listening-ip=XX.XX.XX.XX
relay-threads=1
verbose
Verbose
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=SomeSuperSecretPassword
realm=mynextcloudfqdn
user-quota=10
total-quota=100
max-bps=1024000
bps-capacity=8192000
cert=/etc/pki/tls/certs/wildcard.fqdn.combined.crt
pkey=/etc/pki/tls/private/wildcard.fqdn.key
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
no-stdout-log
log-file=/var/log/turn.log
no-loopback-peers
no-multicast-peers
pidfile="/var/run/turnserver/turnserver.pid"
cli-password=qwerty
```

I've tried various combinations, different locations and different firewall / IP sets.

Using nextcloud v13.0.6 with chat module 3.2.5 configured to use TCP and UDP, and both STUN and TURN via my coturn server on port 443.
Coturn 4.5.0.7 installed (alone) on a CentOS 7.5 x64 box.

I post this here because I don't think it is nextcloud related.
I'm getting headaches from not finding the issue, does anyone have an idea of what could possibly make those random failures with more than 2 computers ?

Thanks a lot.

**Comment by misi** [comment] 2018-09-13 08:32
Have you tried the git master branch?

- I think You shouldn't set the relay thread number. It will be auto detected based on your cpu core numbers..
- And if I were You I would start investigating issue with checking browser log.
- Debug ice agent 
chrome:webrtc-internals or about:webrtc
And get detailed ICE agent log.
See: https://misi.github.io/webrtc-c0d3l4b/#30

Config
```
tls-listening-port=443
listening-ip=XX.XX.XX.XX
#relay-threads=1
verbose
Verbose
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=SomeSuperSecretPassword
realm=mynextcloudfqdn
#user-quota=10
#total-quota=100
#max-bps=1024000
#bps-capacity=8192000
cert=/etc/pki/tls/certs/wildcard.fqdn.combined.crt
pkey=/etc/pki/tls/private/wildcard.fqdn.key
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"
no-stdout-log
log-file=/var/log/turn.log
no-loopback-peers
no-multicast-peers
pidfile="/var/run/turnserver/turnserver.pid"
cli-password=qwerty
```

**Comment by misi** [comment] 2018-09-14 02:51
@deajan 
Are you sure that it is not application problem in the nextcloud talk?
So have you tested it without turn successfully? 
I want to know why do you think it is a coTURN issue and not NextCloud Talk issue..

**Comment by tdm4** [comment] 2019-04-03 17:20
@deajan I get this issue too on NextCloud Talk and Coturn. I'm not entirely sure if it's Coturn or Nextcloud Talk. How do I go about determining this? Is there a tool that simulates 3 or 4 WebRTC clients?

**Comment by tdm4** [comment] 2019-04-03 17:41
My problem is the same:

Person A calls Person B. Conversation works fine, video is fine. 
When Person C tries to join, it works for like 30 seconds, and then the calls all drop and it takes 5-10 minutes to rejoin the call, at which point only 2 people are in the call and the 3rd person couldn't join.

I see bits in the TURN server where Person B drops out of the call and it ends up deleting all the peers. (All 3 IPs that were connected)

I think the problem is with the ICE refreshes. I don't know if it's this issue:
https://github.com/nextcloud/spreed/issues/1630

Is there a way to test this to eliminate coturn being at fault here?

**Comment by deajan** [comment] 2019-04-03 22:12
I totally forgot about this one for a while :)
I had other probems involving port 80/443 filtering on 4G networks here in France (tried all major operators, there seem to be proxys). See https://github.com/grke/burp/issues/782#issuecomment-465928926 for my tests.
So initially I've put my coturn server to listen on port 443 in order to make firewalls happy, but I ended up putting it back it's default port because of this.

Also, what kind of clients do you have ? Phones and computers ? 4G networks ?
Do your clients reside behind firewalls ? With maybe content inspection ? Had trouble with that too.

**Comment by misi** [comment] 2019-04-04 08:19
@tdm4 My guess that it is application issue (or network filtering) and it is not coturn related issue.

**Comment by misi** [comment] 2019-04-05 06:51
@tdm4 @deajan 
Can anyone explain why do any of you think this is a coturn issue?
I don't find any explanation, and I am wondering if it there is no sign that there is an issue with turn server, then may it would be better to close this thread here and move all of this conversation to NextCloud issue tracker side..

**Comment by tdm4** [comment] 2019-04-06 19:04
Hi @misi -
Yeah I've ruled out networking/firewall issues as I do let through not only 3478 (udp and tcp) but also the UDP relay port range. So, my guess is it's NextCloud Talk/Spreed that's having issues.

**Comment by deajan** [comment] 2019-04-06 20:15
@misi Thats' the point, outruling coturn.
@tdm4 still do you use mobile devices for your tests ? If yes, can you try with desktops/laptops only ?

**Comment by misi** [comment] 2019-04-08 09:18
@deajan Ok. 
I think Nextcloud use a Spreed version that is outdated.
Let me know if I can help anything..

**Comment by tdm4** [comment] 2019-04-14 17:45
@deajan @misi  -  I can definitely confirm. Upgrading to NextCloud Talk v5.0.3 fixes this instability. I just tested 3 clients and it works perfectly. This is definitely not a coturn issue.

**Comment by misi** [comment] 2019-04-15 06:36
Should we close it?

**Comment by deajan** [comment] 2019-04-15 20:44
Can you give me a couple of days to confirm ?
I'll upgrade Nextcloud, make the tests again, and then outrule the 4G filtering issues by configuring coturn back to port 443 and use different styles of connections and firewalls to finish testing my issue.

**Comment by tdm4** [comment] 2019-04-17 07:09
@deajan  - Don't forget to allow the UDP relay endpoints in/out of the firewall as well (by default: 49152-65535 but they're configurable). That bit got me until I realised what was happening.

**Comment by deajan** [comment] 2019-04-17 08:05
@tdm4 Let me get that straight...
My coturn server has a public IP, and it's (iptables) firewall is configured to open ```ports: 5349/udp 5349/tcp 3478/tcp 3478/udp```.

Some clients have 4G access (so technically no port filter), some are behind SOHO routers which means no outgoing filters, but most are behind enterprise firewall routers which filter all outgoing traffic.
On those, allowing ports 5349 & 3478 is doable, but allowing a full range of 16000 ports isn't.
Aren't those UDP ports for direct client2client connections ?
And isn't the TURN server supposed to handle exactly those scenarios where both clients are behind restrictive NATs ?

Best regards.

**Comment by misi** [comment] 2019-04-18 05:09
If you really expect restrictive NAT, then port forward TURN to port 443 => 5349 and 80 => 3478. 
And configure your ICE Agent/Browser/App with multiple turn servers. Start with port 443 and tcp.
e.g.

**Comment by deajan** [comment] 2019-04-18 06:53
That was my initial way of doing, but then I got into trouble with the 4G connections on port 443 so I outruled that part.
I have upgraded my test instance yesterday, and will do the tests today. I'll report back then, with both standard ports and special ports.

**Comment by tdm4** [comment] 2019-04-25 08:22
I can confirm that allowing in the UDP relay points, and 3478 and 5349 that everything works on my side. @deajan - I think because your firewall is so restricted and doesn't allow the UDP relay points in and out, you're going to run into problems when the clients have to set up streams between each other via the TURN server.

**Comment by deajan** [comment] 2019-04-25 08:35
Hence the fact that I try to use ports 443 and 80 :)
Tests going on.

**Comment by deajan** [comment] 2019-05-07 14:21
Got to make some new tests today.
Updated NC (v15.0.7) + Talk to latest (v5.0.3), opened ports 5349, 3478, 443 and 80 tcp and udp on my coturn server (which has a public IP) and on the networks I administer.

Well, I still got random no video clients, mostly when using more than two simultaneous clients.
I've read some of the webrtc logs, it seems that some clients are set to "frozen" state.
I also get a lot of stun error code 401 and 486.
From what I understand of the logs, there are some bad stun messages received by the client.
```
(stun/INFO) STUN-CLIENT(srflx(IP4:192.168.43.181:50482/UDP|turn.mycoturn.server.tld:80)): Received response; processing

(ice/ERR) ICE(PC:1557235987547000 (id=4294967308 url=https://vhost.mycoturn.server.tld/call/srercfva)): peer (PC:1557235987547000 (id=4294967308 url=https://vhost.mycoturn.server.tld/call/srercfva):default) pairing local trickle ICE candidate srflx(IP4:192.168.43.181:50482/UDP|turn.mycoturn.server.tld:80)

(stun/WARNING) Inconsistent message method: 113 expected 001

(stun/WARNING) Inconsistent message method: 113 expected 001

(stun/WARNING) Inconsistent message method: 113 expected 001

(stun/INFO) STUN-CLIENT(relay(IP4:192.168.43.181:50482/UDP|turn.mycoturn.server.tld:443)::TURN): Received response; processing

(stun/WARNING) STUN-CLIENT(relay(IP4:192.168.43.181:50482/UDP|turn.mycoturn.server.tld:443)::TURN): Error processing response: Retry may be possible, stun error code 401.

(ice/NOTICE) ICE(PC:1557235987547000 (id=4294967308 url=https://vhost.mycoturn.server.tld/call/srercfva)): Message does not correspond to any registered stun ctx

(stun/INFO) Unrecognized attribute: 0x802b

(stun/INFO) Unrecognized attribute: 0x802b

(stun/INFO) Unrecognized attribute: 0x802b

(stun/WARNING) Inconsistent message method: 113 expected 001

(stun/WARNING) Inconsistent message method: 113 expected 001

(stun/WARNING) Inconsistent message method: 113 expected 001
```

**Comment by deajan** [comment] 2019-05-07 15:48
In the turnserver.conf config file I see the following:
```
# Lower and upper bounds of the UDP relay endpoints:
# (default values are 49152 and 65535)
#
#min-port=49152
#max-port=65535
```
Am I supposed to open port range 49125-65535/udp on the turn server ?

Btw, upgraded to coturn latest git-master today, does not seem to make a difference.

**Comment by deajan** [comment] 2019-07-18 11:25
ping !
Anyone having this random more than 2 people can't use video issue ?

**Comment by tdm4** [comment] 2019-07-22 10:37
@deajan - Yeah I am, but it's not a coturn issue. I've gotten 2 Firefox participants + 1 Android Nextcloud Talk client working 3 way, but 3 participants using Firefox or Chrome don't work. I don't think this is a coturn issue as the android talk client seems to work. 

This is a Nextcloud Talk issue, not a coturn issue, @deajan

**Comment by tdm4** [comment] 2019-07-22 10:38
@deajan - yes, you have to open UDP port range 49125-65535/udp on the turn server. Or, you can narrow the port range and open that up. If you don't open the UDP port range on the Turn server you will never get >2 participants working.

**Comment by ggarber** [comment] 2022-08-24 13:43
this has been open for too long and doesn't look like a coturn issue, closing for now but let me know if i should reopen it

**Closed by ggarber** 2022-08-24 13:43 UTC
