### ISSUE TITLE
Anyone can help with TURN/Relay client on Windows

### ISSUE THREAD

**Issue by adhicl** [coturn/coturn#226] opened 2018-03-17 03:46 UTC
Hi, I have already able to run coturn in my ubuntu server.
But right now I want to possibly create a plugin/ source to connect it to my c# applications.
I wonder if anyone can help with TURN client in windows, either existing working code or how to build the turnclient here for windows using Visual Studio. Any hint is appreciated since I never build from a c code before. Thanks.

**Comment by firegurafiku** [comment] 2018-03-21 10:18
Possible duplicate of #166.
To the best of my knowledge, the code is not ready for pure Windows build at the moment. It should yet compile in Cygwin, but it is a not production-ready option.

But if you only want to build a Windows version of `libturnclient.a` and then use in C#, you basically need to do the following:

1. Get the OpenSSL prebuilt library for your Visual Studio from somewhere (I guess, official builds exist).

2. Create new static library project and add the following files into it:

       src/client/ns_turn_ioaddr.c
       src/client/ns_turn_ioaddr.h
       src/client/ns_turn_msg.c
       src/client/ns_turn_msg.h
       src/client/ns_turn_msg_addr.c
       src/client/ns_turn_msg_addr.h
       src/client/ns_turn_msg_defs.h
       src/client/ns_turn_msg_defs_experimental.h
       src/client++/TurnMsgLib.h
       src/ns_turn_defs.h

3. Compile your library (don't forget to link it against OpenSSL).
4. Write a C# library to wrap unsafe calls to the underlying C code.

**Comment by misi** [comment] 2018-03-21 10:39
Why you want to have turn relay client on win? 
May you are looking for an ICE client UA lib:

- http://interoperability.blob.core.windows.net/files/MS-ICE/[MS-ICE].pdf
- https://msdn.microsoft.com/en-us/library/office/cc431495(v=office.12).aspx

**Comment by adhicl** [comment] 2018-03-23 05:58
Hi, basically I want to try to use this for my Unity game app. I already managed to run the coturn server on an ubuntu server.
So, I would like to connect it to my app. And I develop them using Windows and Unity.

**Comment by misi** [comment] 2018-03-23 06:49
Try to use WebRTC Data Channel it has native implementation https://webrtc.org/native-code/

**Comment by adhicl** [comment] 2018-03-24 04:13
Hi, thanks @misi, I will check all the links

**Comment by misi** [comment] 2018-10-12 13:40
I hope we didn't leave any open questions, if we left any then open a new issue about it. 
Thanks!

**Closed by misi** 2018-10-12 13:40 UTC
