### ISSUE TITLE
dose cotrun use for group call

### ISSUE THREAD

**Issue by hangoctl** [coturn/coturn#936] opened 2022-08-07 17:11 UTC
I use react-native-webrtc to create video call group
peer to peer work perfectly, but if more than 2 people(ex:3 people in group), the third person(who join latest in the call group) can not heard other
My config: 
const configuration = {
  iceServers: [
    {
      urls: 'stun:128.199.144.126:3478?transport=udp',
    },
    {
      urls: 'turn:128.199.144.126:3478?transport=udp',
      username: 'test',
      credential: 'test123',
    },
  ],
};

**Comment by ggarber** [comment] 2022-08-08 18:15
For group calls you usually use a different type of server, a SFU.  You can read about it here: https://www.callstats.io/blog/webrtc-architectures-explained-in-5-minutes-or-less

If you still want to use a P2P approach where everybody needs to send and receive from everybody else that's fine but from coturn point of view a group call with 3 participants is the same as 3 p2p calls.   So it is unlikely that coturn is affecting your group call and the problem is probably somewhere else.

If you can provide more info about why the audio is not working (is the PeerConnection established? are the audio packets received?,...) then maybe somebody in this forum can help you but still is unlikely to be a coturn issue.

**Comment by hangoctl** [comment] 2022-08-09 18:14
> For group calls you usually use a different type of server, a SFU. You can read about it here: https://www.callstats.io/blog/webrtc-architectures-explained-in-5-minutes-or-less
> 
> If you still want to use a P2P approach where everybody needs to send and receive from everybody else that's fine but from coturn point of view a group call with 3 participants is the same as 3 p2p calls. So it is unlikely that coturn is affecting your group call and the problem is probably somewhere else.
> 
> If you can provide more info about why the audio is not working (is the PeerConnection established? are the audio packets received?,...) then maybe somebody in this forum can help you but still is unlikely to be a coturn issue.

ok thank you
have a nice day

**Comment by ggarber** [comment] 2022-08-16 06:23
ok, closing it for now.  Reopen if you have additional information or questions.  Thank you!

**Closed by ggarber** 2022-08-16 06:23 UTC
Labels: question
