### ISSUE TITLE
error: ‘SSL_OP_NO_RENEGOTIATION’ undeclared

### ISSUE THREAD

**Issue by WwwJy** [coturn/coturn#977] opened 2022-09-13 11:54 UTC
openssl： 1.1.1q
coturn：[4.6.0-r0](https://github.com/coturn/coturn/blob/tree/docker/4.6.0-r0)

> In file included from src/apps/common/ns_turn_openssl.h:36:0,
                 from src/apps/common/apputils.h:36,
                 from src/apps/relay/ns_ioalib_engine_impl.c:37:
src/apps/relay/ns_ioalib_engine_impl.c: In function ‘set_socket_ssl’:
src/apps/relay/ns_ioalib_engine_impl.c:1431:25: error: ‘SSL_OP_NO_RENEGOTIATION’ undeclared (first use in this function)
    SSL_set_options(ssl, SSL_OP_NO_RENEGOTIATION);
                         ^
src/apps/relay/ns_ioalib_engine_impl.c:1431:25: note: each undeclared identifier is reported only once for each function it appears in
In file included from src/apps/common/ns_turn_openssl.h:36:0,
                 from src/apps/common/apputils.h:36,
                 from src/apps/relay/dtls_listener.c:31:
src/apps/relay/dtls_listener.c: In function ‘dtls_server_input_handler’:
src/apps/relay/dtls_listener.c:298:59: error: ‘SSL_OP_NO_RENEGOTIATION’ undeclared (first use in this function)
  SSL_set_options(connecting_ssl, SSL_OP_COOKIE_EXCHANGE | SSL_OP_NO_RENEGOTIATION);
                                                           ^
src/apps/relay/dtls_listener.c:298:59: note: each undeclared identifier is reported only once for each function it appears in
src/apps/relay/dtls_listener.c: In function ‘create_new_connected_udp_socket’:
src/apps/relay/dtls_listener.c:584:60: error: ‘SSL_OP_NO_RENEGOTIATION’ undeclared (first use in this function)
   SSL_set_options(connecting_ssl, SSL_OP_COOKIE_EXCHANGE | SSL_OP_NO_RENEGOTIATION);

**Comment by tyranron** [comment] 2022-09-13 12:26
@WwwJy `4.6.0-r0` is the version of the `coturn/coturn` Docker image only. The last release of Coturn itself has `4.6.0` version: https://github.com/coturn/coturn/tree/4.6.0

The issue is about the Coturn itself, as I see.

I'll add more GitHub release notes to make these versions more clear.

**Comment by tyranron** [comment] 2022-09-13 12:54
> I'll add more GitHub release notes to make these versions more clear.

Done: https://github.com/coturn/coturn/commit/8b66fa4ff2104a64534755d0ba07afde5d2420eb and https://github.com/coturn/coturn/releases/tag/docker%2F4.6.0-r0

**Comment by eakraly** [comment] 2022-09-13 23:16
Already described in #952

**Comment by WwwJy** [comment] 2022-09-14 09:09
openssl: OpenSSL 1.1.1k
coturn: https://github.com/coturn/coturn/releases/tag/4.6.0

> ps/relay/dbdrivers/dbd_pgsql.c src/apps/relay/dbdrivers/dbd_mysql.c src/apps/relay/dbdrivers/dbd_mongo.c src/apps/relay/dbdrivers/dbd_redis.c src/apps/common/apputils.c src/apps/common/ns_turn_utils.c src/apps/common/stun_buffer.c src/client/ns_turn_ioaddr.c src/client/ns_turn_msg_addr.c src/client/ns_turn_msg.c  src/server/ns_turn_allocation.c src/server/ns_turn_maps_rtcp.c src/server/ns_turn_maps.c src/server/ns_turn_server.c -o bin/turnserver  -lrt -lnsl -lresolv -pthread -lcrypto   -lssl -lcrypto   -levent_openssl -levent_pthreads -levent    -Wl,-rpath,/usr/local/lib
In file included from src/apps/common/ns_turn_openssl.h:36:0,
                 from src/apps/common/apputils.h:36,
                 from src/apps/relay/ns_ioalib_engine_impl.c:37:
src/apps/relay/ns_ioalib_engine_impl.c: In function 'set_socket_ssl':
src/apps/relay/ns_ioalib_engine_impl.c:1431:25: error: 'SSL_OP_NO_RENEGOTIATION' undeclared (first use in this function)
    SSL_set_options(ssl, SSL_OP_NO_RENEGOTIATION);
                         ^
src/apps/relay/ns_ioalib_engine_impl.c:1431:25: note: each undeclared identifier is reported only once for each function it appears in
In file included from src/apps/common/ns_turn_openssl.h:36:0,
                 from src/apps/common/apputils.h:36,
                 from src/apps/relay/dtls_listener.c:31:
src/apps/relay/dtls_listener.c: In function 'dtls_server_input_handler':
src/apps/relay/dtls_listener.c:298:59: error: 'SSL_OP_NO_RENEGOTIATION' undeclared (first use in this function)
  SSL_set_options(connecting_ssl, SSL_OP_COOKIE_EXCHANGE | SSL_OP_NO_RENEGOTIATION);
                                                           ^
src/apps/relay/dtls_listener.c:298:59: note: each undeclared identifier is reported only once for each function it appears in
src/apps/relay/dtls_listener.c: In function 'create_new_connected_udp_socket':
src/apps/relay/dtls_listener.c:584:60: error: 'SSL_OP_NO_RENEGOTIATION' undeclared (first use in this function)
   SSL_set_options(connecting_ssl, SSL_OP_COOKIE_EXCHANGE | SSL_OP_NO_RENEGOTIATION);
                                                            ^
make: *** [bin/turnserver] Error 1

**Comment by WwwJy** [comment] 2022-09-14 09:10
I tried to use different versions of openssl, and then compiled the coturn, but I got the same error

**Comment by WwwJy** [comment] 2022-09-14 09:11
I tried to use different versions of openssl, and then compiled the coturn, but I got the same error

**Comment by ggarber** [comment] 2022-09-14 10:30
@WwwJy I just landed the fix from @eakraly .  Can you check if the issue is fixed?

Also.. You can always try to use the docker images as a workaround if that's an option for you.

**Closed** 2022-09-14 10:29 UTC

**Comment by WwwJy** [comment] 2022-09-14 14:49
> @WwwJy I just landed the fix from @eakraly . Can you check if the issue is fixed?
> 
> Also.. You can always try to use the docker images as a workaround if that's an option for you.

I compiled with the master branch, and the compilation succeeded
