### ISSUE TITLE
TURN server stops after some time

### ISSUE THREAD

**Issue by ishan501** [coturn/coturn#664] opened 2020-12-12 13:02 UTC
I've installed CoTURN on Ubuntu 16.04 server. I'm starting the TURN server with the below command:

turnserver -a -o -v -n --cert /etc/letsencrypt/live/mydomain.com/fullchain.pem --pkey /etc/letsencrypt/live/mydomain.com/privkey.pem -u username:password -r "mydomain.com"

I check with Trickle ice and it works fine. But after some random time (typically in days) it stops working/shuts down.

Is there any way to run it forever or at least get an email if the service stops?
Thanks!

**Comment by misi** [comment] 2020-12-14 07:44
@ishan501  Which version? What is the logs when it stops? Try to use -V if  -v don't show enough details

**Comment by ishan501** [comment] 2020-12-15 05:47
Hey, CoTURN version: Version Coturn-4.5.0.7 'dan Eider'.

I can see the below logs

996: session 003000000000000001: realm <media1.sintonus.com> user <>: incoming packet BINDING processed, success
1006: session 005000000000000001: realm <media1.sintonus.com> user <MediaSintonus>: incoming packet BINDING processed, success
1006: session 003000000000000001: realm <media1.sintonus.com> user <>: incoming packet BINDING processed, success
1010: session 005000000000000001: refreshed, realm=<media1.sintonus.com>, username=<MediaSintonus>, lifetime=0
1010: session 005000000000000001: realm <media1.sintonus.com> user <MediaSintonus>: incoming packet REFRESH processed, success
1011: session 005000000000000001: closed (2nd stage), user <MediaSintonus> realm <media1.sintonus.com> origin <>, local 161.97.145.200:3478, remote 43.241.144.111:32185, reason: allocation timeout
1011: session 005000000000000001: delete: realm=<media1.sintonus.com>, username=<MediaSintonus>
1011: session 005000000000000001: peer 192.168.0.106 deleted
1017: session 003000000000000001: realm <media1.sintonus.com> user <>: incoming packet BINDING processed, success
1026: session 003000000000000001: closed (2nd stage), user <> realm <media1.sintonus.com> origin <>, local 161.97.145.200:3478, remote 43.241.144.111:33002, reason: allocation watchdog determined stale session state

It's not for this particular server. I mostly use Ubuntu 18.04 and in all the servers this happens. I need to start the CoTURN again after some time.

Maybe CoTURN encounters an error and it crashes?

**Comment by misi** [comment] 2020-12-15 08:13
Try to upgrade to a more up2date version..
Try to log with more verbose -V

**Comment by ishan501** [comment] 2020-12-22 08:39
I'm starting the server with pm2 now. Do you recommend it?

**Comment by pierreozoux** [comment] 2021-04-18 16:06
I see the same, I did setup some monitoring and it is crashing after a day or so.

**Comment by peterzy** [comment] 2021-04-21 10:36
Hi, I can confirm it happens to me also. 
Coturn version: 
Version Coturn-4.5.0.7 'dan Eider'

Ubuntu 18.04:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by sualko** [comment] 2021-04-23 07:15
Same for me, but I don't think it's related to the time it's running, because I restart the coturn server every night. Since the log doesn't show any timestamp, it's hard for me to correlate the log with the reported issues.

I see a few `incoming packet message processed, error 401: Unauthorized` lines, but I'm not sure that they are related.

Version Coturn-4.5.0.7 'dan Eider' on Ubuntu 18.04.

**Comment by pierreozoux** [comment] 2021-04-23 16:39
I updated to ubuntu 20 and coturn 4.5.1, so far so good, I recommend the same :)

**Comment by peterzy** [comment] 2021-04-24 06:52
I have updated to Ubuntu 20.04 and  Version Coturn-4.5.1.1 'dan Eider'. I will keep you posted how it goes. However there is one trick during the upgrade: once you upgrade to 4.5.1.1 it will look like working, but it will NOT listen to port 443.

In order to make it work you need to: 

`
sudo systemctl stop coturn
sudo rm /lib/systemd/system/coturn.service
sudo systemctl daemon-reload
sudo systemctl start coturn
`
Posting in case someone also goes this way :-)

**Comment by pierreozoux** [comment] 2021-04-26 16:02
No restart so far, I think you can close the issue: @misi

**Comment by knoy** [comment] 2021-06-22 15:11
This is happening on Debian 9 as well. No obvious error in log output

**Comment by ofrzeta** [comment] 2021-11-05 15:03
We have the same Problem on Ubuntu 20.04 with 4.5.1.1-1.1ubuntu0.20.04.2. Worse, the turnserver keeps running but doesn't accept new connections (on port 443 at least).

**Comment by ishan501** [comment] 2021-11-06 16:58
Now, I'm using PM2 to keep it running all the time and it works fine.
`pm2 start turnserver`

**Comment by ofrzeta** [comment] 2021-11-07 17:41
I left the server running until it didn't accept any connections and took a look with strace which turned up this:
```

write(2, "bind: Permission denied\n", 24) = 24
write(3, "1: Trying to bind fd 17 to <127."..., 52) = 52
write(2, "Cannot bind local socket to addr"..., 52) = 52
write(3, "1: Cannot bind DTLS/UDP listener"..., 61) = 61
write(3, "1: Trying to bind DTLS/UDP liste"..., 74) = 74
```

**Comment by eakraly** [comment] 2022-09-25 07:00
Seems like the issue has been addressed.
If it still persists - please open a new one. Thank you!

**Closed by eakraly** 2022-09-25 07:00 UTC
Labels: question
