### ISSUE TITLE
tls-listening-port and alt-tls-listening-port ignored in config

### ISSUE THREAD

**Issue by gsparx** [coturn/coturn#347] opened 2019-02-23 00:38 UTC
I have a `turnserver.conf` that looks like this. My expectation is that this would open TCP and UDP listeners on ports 3478, 3479, 443 and 444.

```
use-auth-secret
log-file=stdout
redis-userdb="ip=127.0.0.1 dbname=0 password=<redacted> port=6380 connect_timeout=3600"
redis-statsdb="ip=127.0.0.1 dbname=0 password=<redacted> port=6380 connect_timeout=3600"
realm=somerealm
verbose
listening-port=3478
alt-listening-port=3479
tls-listening-port=443
alt-tls-listening-port=444
external-ip=<somepublicip>/<someprivateip>
```

However, in the coturn logs, I see the following for listener creation

```
0: IPv4. UDP listener opened on: 127.0.0.1:3478
0: IPv4. UDP listener opened on: 127.0.0.1:3479
0: IPv4. UDP listener opened on: 172.32.72.96:3478
0: IPv4. UDP listener opened on: 172.32.72.96:3479
0: IPv4. UDP listener opened on: 172.17.0.1:3478
0: IPv4. UDP listener opened on: 172.17.0.1:3479
0: IPv6. UDP listener opened on: ::1:3478
0: IPv6. UDP listener opened on: ::1:3479
0: IPv4. SCTP listener opened on : 127.0.0.1:3478
0: IPv4. TCP listener opened on : 127.0.0.1:3478
0: IPv4. SCTP listener opened on : 127.0.0.1:3479
0: IPv4. TCP listener opened on : 127.0.0.1:3479
0: IPv4. SCTP listener opened on : 172.32.72.96:3478
0: IPv4. TCP listener opened on : 172.32.72.96:3478
0: IPv4. SCTP listener opened on : 172.32.72.96:3479
0: IPv4. TCP listener opened on : 172.32.72.96:3479
0: IPv4. SCTP listener opened on : 172.17.0.1:3478
0: IPv4. TCP listener opened on : 172.17.0.1:3478
0: IPv4. SCTP listener opened on : 172.17.0.1:3479
0: IPv4. TCP listener opened on : 172.17.0.1:3479
0: IPv6. SCTP listener opened on : ::1:3478
0: IPv6. TCP listener opened on : ::1:3478
0: IPv6. SCTP listener opened on : ::1:3479
0: IPv6. TCP listener opened on : ::1:3479
```

This indicates to me that listeners are not being opened at all on ports 443 and 444, effectively ignoring the `tls-listening-port` and `alt-tls-listening-port` configurations.

Am I understanding the configuration correctly, or am I missing something here? I noticed that I am able to get a listener on port 443 if I  set `alt-listening-port=443` so it doesn't appear to be specific to the port.

**Comment by misi** [comment] 2019-02-25 09:00
Add a TLS certificate and priv key to your config..

**Comment by misi** [comment] 2019-02-28 09:05
I will close this issue, but please comment or open a new if the issue still has not been resolved..

**Closed by misi** 2019-02-28 09:05 UTC

**Comment by FackelAB** [comment] 2020-04-28 05:33
I think it would be good to write into the log something like:
no certificate specified, this is required for tsl-comminication
and error-log on failure, while opening required files (not found, no permission)

**Comment by TLHN** [comment] 2020-09-01 00:00
i have the same issue for some reason

`root@coturn:~# vim /etc/turnserver.conf
listening-port=3478
tls-listening-port=443
external-ip=88.99.14.147
fingerprint
use-auth-secret
static-auth-secret=171451ce8ddc3ba888b927fbed4b10f3
cert=/etc/letsencrypt/live/turn.dialoggestalter.de/fullchain.pem
pkey=/etc/letsencrypt/live/turn.dialoggestalter.de/privkey.pem
cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"
dh2066
syslog
no-tlsv1
no-tlsv1_1
`

`root@coturn:~# turnserver -v -o
0: Config file found: /root/../etc/turnserver.conf
0:
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0:
Max number of open files/sockets allowed for this process: 1048576
0:
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0:

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1f  31 Mar 2020 (0x1010106f)
0:
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0:
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name:
0: Default realm:
0: ERROR:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0:
CONFIGURATION ALERT: you did specify the long-term credentials usage
 but you did not specify the default realm option (-r option).
                Check your configuration.
0: SSL23: Certificate file found: /etc/letsencrypt/live/turn.dialoggestalter.de/fullchain.pem
0: SSL23: Private key file found: /etc/letsencrypt/live/turn.dialoggestalter.de/privkey.pem
0: TLS1.2: Certificate file found: /etc/letsencrypt/live/turn.dialoggestalter.de/fullchain.pem
0: TLS1.2: Private key file found: /etc/letsencrypt/live/turn.dialoggestalter.de/privkey.pem
0: TLS cipher suite: ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
0: DTLS: Certificate file found: /etc/letsencrypt/live/turn.dialoggestalter.de/fullchain.pem
0: DTLS: Private key file found: /etc/letsencrypt/live/turn.dialoggestalter.de/privkey.pem
0: DTLS1.2: Certificate file found: /etc/letsencrypt/live/turn.dialoggestalter.de/fullchain.pem
0: DTLS1.2: Private key file found: /etc/letsencrypt/live/turn.dialoggestalter.de/privkey.pem
0: DTLS cipher suite: ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 88.99.14.147
0: Listener address to use: ::1
0: Listener address to use: 2a01:4f8:c17:ce3d::1
0: =====================================================
0: Total: 2 'real' addresses discovered
0: =====================================================
0: NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering relay addresses: =============
0: Relay address to use: 88.99.14.147
0: Relay address to use: 2a01:4f8:c17:ce3d::1
0: =====================================================
0: Total: 2 relay addresses discovered
`
`root@coturn:~# netstat -npta | grep turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 88.99.14.147:3478       0.0.0.0:*               LISTEN      2833/turnserver
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 ::1:3478                :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
tcp6       0      0 2a01:4f8:c17:ce3d::3478 :::*                    LISTEN      2833/turnserver
`

i used the bbb guidance and lots of google but i have no idea why he ist not using 443

**Comment by d0nn13** [comment] 2020-09-16 22:12
For people having port 443 not opened, it might be caused by the systemd unit that is shipped in debian/ubuntu packages (at least).

In the service unit, the turnserver executable is run by a non-root user, and non-root users cannot open ports below 1024...

Fix:
```diff
  [Unit]
  Description=coTURN STUN/TURN Server
  Documentation=man:coturn(1) man:turnadmin(1) man:turnserver(1)
  After=network.target

  [Service]

- User=turnserver
- Group=turnserver
+ User=root
  Type=fork
  RuntimeDirectory=turnserver
  PIDFile=/run/turnserver/turnserver.pid
  ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid
  #FixMe: turnserver exit faster than it is finshing the setup and ready for handling the connection.
  ExecStartPost=/bin/sleep 2
  Restart=on-failure
  InaccessibleDirectories=/home
  PrivateTmp=yes

  [Install]
  WantedBy=multi-user.target

**Comment by mingyub** [comment] 2021-03-10 08:44
I used port 5349 for tls and it wasn't starting. The reason was because user `turnserver` can't access certificate files.
