### ISSUE TITLE
Prometheus API is missing session count

### ISSUE THREAD

**Issue by paulkram** [coturn/coturn#1026] opened 2022-10-17 13:55 UTC
Hello,
while updating from Coturn 4.5.2 to 4.6.0 we tried to swith from pulling stats from CLI interface to just use the prometheus endpoint. Unfortunately it is missing session counts, total session count, udp session count. Maybe even others. Would it be possible to add them?

Thanks!

Paul

**Comment by eakraly** [comment] 2022-10-17 22:40
Hi @paulkram 
Totally agree - prometheus interface begs for more metrics
Anything you could contribute?

**Comment by kingsh2012** [comment] 2022-10-26 07:56
hi,my docker coturn:4.6.0 open prometheus,but xx.xx.xx.xx:9641/metrics no value, need help
 thx.
```
# HELP turn_traffic_rcvp Represents finished sessions received packets
# TYPE turn_traffic_rcvp counter

# HELP turn_traffic_rcvb Represents finished sessions received bytes
# TYPE turn_traffic_rcvb counter

# HELP turn_traffic_sentp Represents finished sessions sent packets
# TYPE turn_traffic_sentp counter

# HELP turn_traffic_sentb Represents finished sessions sent bytes
# TYPE turn_traffic_sentb counter

# HELP turn_traffic_peer_rcvp Represents finished sessions peer received packets
# TYPE turn_traffic_peer_rcvp counter

# HELP turn_traffic_peer_rcvb Represents finished sessions peer received bytes
# TYPE turn_traffic_peer_rcvb counter

# HELP turn_traffic_peer_sentp Represents finished sessions peer sent packets
# TYPE turn_traffic_peer_sentp counter

# HELP turn_traffic_peer_sentb Represents finished sessions peer sent bytes
# TYPE turn_traffic_peer_sentb counter

# HELP turn_total_traffic_rcvp Represents total finished sessions received packets
# TYPE turn_total_traffic_rcvp counter

# HELP turn_total_traffic_rcvb Represents total finished sessions received bytes
# TYPE turn_total_traffic_rcvb counter

# HELP turn_total_traffic_sentp Represents total finished sessions sent packets
# TYPE turn_total_traffic_sentp counter

# HELP turn_total_traffic_sentb Represents total finished sessions sent bytes
# TYPE turn_total_traffic_sentb counter

# HELP turn_total_traffic_peer_rcvp Represents total finished sessions peer received packets
# TYPE turn_total_traffic_peer_rcvp counter

# HELP turn_total_traffic_peer_rcvb Represents total finished sessions peer received bytes
# TYPE turn_total_traffic_peer_rcvb counter

# HELP turn_total_traffic_peer_sentp Represents total finished sessions peer sent packets
# TYPE turn_total_traffic_peer_sentp counter

# HELP turn_total_traffic_peer_sentb Represents total finished sessions peer sent bytes
# TYPE turn_total_traffic_peer_sentb counter

# HELP turn_total_allocations Represents current allocations number
# TYPE turn_total_allocations gauge

# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576

# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1

# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total gauge
process_cpu_seconds_total 0

# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 593936384

# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 120344224

# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 63
```

**Comment by eakraly** [comment] 2022-10-26 18:51
Hi @kingsh2012 
When you pulled the metrics it seems like you did not have any data (for example `process_cpu_seconds_total 0`)
Make a few connections through the server and then pull the data

**Comment by kingsh2012** [comment] 2022-10-27 02:20
HI @eakraly 
Yes, I did，my use pystun test coturn noraml, but mertrics no value。
docker-compose.yml
```
version: "3"

services:
  coturn:
    image: "coturn/coturn:4.6.0"
    network_mode: "host"
    restart: "always"
    privileged: "true"
    command: ["turnserver", "-c" ,"/etc/coturn/turnserver.conf"]
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./turnserver.conf:/etc/coturn/turnserver.conf"
      - "./logs:/var/tmp"
      - "./db:/var/lib/coturn"
```

**Comment by eakraly** [comment] 2022-10-27 23:33
OK, I think I know what the issue is... And it is very funny...
turnserver does not provide ANY metrics for STUN (on prometheus interface), only TURN
You do not see them change - because you run STUN only, and TURN is disabled...
This requires some more development to add STUN metrics.

What metrics would you expect to see for STUN @kingsh2012 ?

**Comment by kingsh2012** [comment] 2022-10-28 02:30
Ok, we only need to use stunserver for now, I needs OPS metrics about stunserver, thx

**Comment by eakraly** [comment] 2022-10-28 22:09
@kingsh2012 if you could contribute a PR that would be great

**Comment by kingsh2012** [comment] 2022-10-31 07:51
@eakraly My level is not enough to submit PR, thank you for maintaining this project, it is a very good project

**Comment by paulkram** [comment] 2022-11-03 12:29
@eakraly 
I opened a PR which extends the allocation count on prometheus API with protocol type as label. It would be great if you could have a look on it. Maybe it will make it in next release.

**Comment by eakraly** [comment] 2022-12-04 19:34
Fixed in #1075

**Comment by eakraly** [comment] 2023-01-17 00:37
Hi @kingsh2012 !
Could you please run the latest version from master branch and provide feedback?
Thanks

**Comment by Neustradamus** [comment] 2023-07-24 21:28
@eakraly, @paulkram, @kingsh2012: This ticket can be closed, I think?

**Closed** 2023-09-30 20:34 UTC
Labels: feature
