### ISSUE TITLE
docker logs shows multiple entries

### ISSUE THREAD

**Issue by rajil** [coturn/coturn#939] opened 2022-08-15 06:48 UTC
Docker is printing the log twice. Any idea why is that?
```
$docker run -d --name=coturn --network=host coturn/coturn

$ docker logs coturn
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : WARNING: Cannot find config file: turnserver.conf. Default and command-line settings will be used.
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Max number of open files/sockets allowed for this process: 1048576
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: : 
```

**Comment by tyranron** [comment] 2022-08-15 09:14
Duplicate of https://github.com/coturn/coturn/issues/859

**Closed by tyranron** 2022-08-15 09:14 UTC
Labels: bug, duplicate
