### ISSUE TITLE
Can't run in debugger

### ISSUE THREAD

**Issue by jonesmz** [coturn/coturn#31] opened 2015-12-08 02:07 UTC
I'm getting a segmentation fault when debugging coturn

The crash is happening on line 1773 of apps/relay/netengine.c
static void setup_auth_server(struct auth_server *as)
{
	if(pthread_create(&(as->thr), NULL, run_auth_server_thread, as)<0) {
		perror("Cannot create auth thread\n");
		exit(-1);
	}
	pthread_detach(as->thr);
}

On the pthread_detach(as->thr); line.

Here's a dump of some related variables.
The format is
name, value, type. 

		setup_auth_server	{void (struct auth_server *)} 0x55555556e3cc <setup_server+1388>	void (struct auth_server *)
		authserver	@0x5555557dad80	auth_server [256]
			[0]	@0x5555557dad80	auth_server
				id	0	authserver_id
				event_base	0x0	event_base *
				in_buf	0x0	bufferevent *
				out_buf	0x0	bufferevent *
				thr	140737255655168	pthread_t
				rch	0	redis_context_handle
			[1]	@0x5555557dadb0	auth_server
				id	1	authserver_id
				event_base	@0x7fffe80008f0	event_base
				in_buf	@0x7fffe8001210	bufferevent
				out_buf	@0x7fffe80015b0	bufferevent
				thr	0	pthread_t
				rch	0	redis_context_handle
			[2]	@0x5555557dade0	auth_server
				id	0	authserver_id
				event_base	0x0	event_base *
				in_buf	0x0	bufferevent *
				out_buf	0x0	bufferevent *
				thr	0	pthread_t
				rch	0	redis_context_handle
		authserver_number	3	authserver_id

Here's some relevant system settings of my machine (Gentoo), which also indicate how turnserver was compiled.
ymir jonesmz # emerge --info turnserver
Portage 2.2.20.1 (python 3.4.3-final-0, hardened/linux/amd64/no-multilib, gcc-4.9.3, glibc-2.21-r1, 4.2.6-hardened-r7 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.2.6-hardened-r7-x86_64-Intel-R-_Core-TM-2_Quad_CPU_Q9550_@_2.83GHz-with-gentoo-2.2
KiB Mem:     8166660 total,     68848 free
KiB Swap:   10494972 total,  10364956 free
Timestamp of repository gentoo: Mon, 07 Dec 2015 19:00:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
distcc 3.2rc1 x86_64-pc-linux-gnu [disabled]
app-shells/bash:          4.3_p39::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.18.4::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.12.6::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo

CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CXXFLAGS="-O2 -pipe -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe"
FCFLAGS="-O2 -pipe"
FFLAGS="-O2 -pipe"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"

Turnserver's installed using this ebuild: https://github.com/jonesmz/gentoo-overlay/blob/master/www-servers/turnserver/turnserver-4.5.0.3.ebuild

I'm debugging with qtcreator (3.4.2). The IDE is being run as root. I'm running a terminal, becoming superuser ( running "su" and giving it my password), then I launch qtcreator from the shell.
Once qtcreator has started, I go to the debug menu, click on "Start Debugging" and then "Start and Debug an External Application"

I select /usr/bin/turnserver as the local executable and then hit OK.

So far, turnserver has always crashed on the pthread_detach line. It seems to break when it's calling it the third time, but I'm not entirely sure.

Any suggestions? Is this a code glitch, or have I done something wrong here?

**Comment by mom040267** [comment] 2015-12-08 07:03
The problem is that pthread_create(...) on error returns not a negative value. It returns an error number that is positive. So, if the thread creation failed, then we treat it as success, but the content of the thread id is undefined. This is why the detach function is crashing. I can fix it in the next build. But why the thread creation is failing is unclear, probably your debugger is doing something wrong.

**Comment by mom040267** [comment] 2015-12-08 07:08
I pushed the fix to the master branch. You can try that and let me know please.

**Closed by mom040267** 2015-12-08 07:08 UTC

**Comment by jonesmz** [comment] 2015-12-08 07:35
I've confirmed that git master doesn't crash as soon as I start it in the debugger. (Didn't bother checking to confirm everything else is working in the debugger, only that it doesn't crash right away).

Much appreciated!

**Comment by jonesmz** [comment] 2017-01-19 08:57
This problem is back in 4.5.0.3

**Comment by mom040267** [comment] 2017-01-19 18:31
can you test the latest code ?

Thanks
Oleg

**Comment by jonesmz** [comment] 2017-01-19 18:42
I'm very sorry, I wrote the wrong version number.

The version that I'm running is 4.5.0.4, the latest release.

I'll try testing the latest git master branch.

**Comment by jonesmz** [comment] 2017-01-19 19:03
Latest git master branch has the same problem:

static void setup_auth_server(struct auth_server *as)
{
	if(pthread_create(&(as->thr), NULL, run_auth_server_thread, as)) {
		perror("Cannot create auth thread\n");
		exit(-1);
	}
	pthread_detach(as->thr);
}

the call to pthread_detach triggers segmentation fault.

I'm running with qtcreator 4.0.3
gdb 7.12
coturn was compiled with gcc 4.9.3

**Comment by mom040267** [comment] 2017-01-20 08:50
pthread_detach is a normal legitimate library or system call. Why would
debugger crash on it ? Can it be a debugger problem ?

**Comment by jonesmz** [comment] 2017-01-20 20:59
What version of gdb do you use? I can install and try that version.

**Comment by mom040267** [comment] 2017-01-22 08:28
If I have to debug the Coturn server (usually for crashes) then I am just
attaching to an already started process. That way your debugger is not
going through that "thread detach" code.

Oleg

**Comment by jonesmz** [comment] 2017-01-23 21:39
So you can't reproduce the issue?
