### ISSUE TITLE
Docker build leaves behind crap in image root directory

### ISSUE THREAD

**Issue by schildbach** [coturn/coturn#512] opened 2020-03-29 17:37 UTC
```
-rw-r--r--   1 root root     0 Mar 29 16:23 '=0.14.0'
-rw-r--r--   1 root root 18184 Mar 29 16:23 '=1.1.0'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=10.3.17'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=2.1.8-stable-4'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=2.15'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=3.6.0'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=8.4~'
-rw-r--r--   1 root root     0 Mar 29 16:23 '=libevent-core-2.1-6'
```

This is on commit 4722697645cf033de8cf4f34e4214af750746365 (master as of today).

**Comment by misi** [comment] 2020-03-29 19:22
Thanks for reporting it! I will test it.

**Comment by eakraly** [comment] 2022-09-04 00:00
Hi @schildbach !
I do not see that happening in 4.5.2
Can you please post where you see it (or if you can reproduce with later versions that the one you originally observed it?)

**Comment by tyranron** [comment] 2022-09-05 17:20
@eakraly since then the Docker image was completely reworked in https://github.com/coturn/coturn/pull/746. It should be fine now. I suggest to close this.

**Closed by tyranron** 2022-09-05 17:20 UTC
Labels: bug
